[phases.setup]
nixPkgs = ["...", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "rm -rf node_modules",
  "npm install --omit=dev --no-audit --no-fund",
  "npm rebuild sqlite3 --build-from-source"
]

[start]
cmd = "npm start"